---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation
name: Verify - License Check

# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  verify-onos-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check License Headers
        uses: opencord/shared-workflows/.github/actions/license-check-action@main
      - name: Run Maven

        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/maven-build-action@3e8765bbc2685951fb7c2be03964304179106b70 # v0.2.1
        with:
          jdk-version: "11"
          mvn-version: "3.3.9"
          mvn-phases: "clean test install spotbugs:check"
          mvn-profiles: "ci-verify"
